### ISSUE TITLE
SpeechToTextV1 not an option when using via Swift Packages.

### ISSUE THREAD

**Issue by MynaBay** [watson-developer-cloud/swift-sdk#1022]
The title pretty much says it. If I install the swift-sdk into my project as a swift package the SpeechToTextv1 isn't listed. I see other packages.

**Comment by mkistler** [comment]
This omission was intentional. Until very recently (just announced at the recent WWDC), Swift Package Manager did not support importing binary packages into a package, and STT requires binary packages (actually C/C++ packages that are "pre-built") to function.

With the new support for binary dependencies in SPM, we could make STT available in a Swift package, but the amount of work needed is unknown.  Of course, we'd be happy for a contribution (PR) in this area.
