### ISSUE TITLE
Publish to CocoaPods

### ISSUE THREAD

**Issue by Ashton-W** [watson-developer-cloud/swift-sdk#127]

**Comment by glennrfisher** [comment]
https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by simonmcl** [comment]
+1  already using Cocoapods in my app (with some of the same libraries), would be much appreciated

**Comment by glennrfisher** [comment]
We can test this with the [chat-app example](https://github.com/IBM-MIL/ios-sdk-chat-app).

**Comment by jfgrang** [comment]
Any update on having swift-idk in cocoapods ?

**Comment by schen22** [comment]
Thanks for bringing this issue back up on our radar! I'll bring it up in our next sprint planning meeting and will begin providing more regular updates for the status of this issue.

**Comment by jtansley** [comment]
Thanks for the reply @schen22 . Any updates? Eagerly awaiting cocoapods support!

**Comment by schen22** [comment]
Hi @jtansley - we will not be adding CocoaPods support due to the overhead required to maintain both Carthage and CocoaPods when publishing a release. Please instead use either Swift Package Manager, or CocoaPods with Carthage. 

If you have any strong reasons you need CocoaPods, feel free to let us know. At this time, we don't see any justification for the overhead required to implement. Closing the issue for now.

**Comment by jfgrang** [comment]
I don't want to have both carthage and cocoapod on the same project just for you.
I really don't what to think about this answer. Even small open source projects do cocoapods + carthage.
This is a matter of hours to build a Pod. Are you really investing on these tools ?
