### ISSUE TITLE
Rename to "swift-sdk"

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#202]
We are currently targeting (and supporting) only the iOS platform; however, we would like to expand compatibility to OS X, tvOS, and watchOS (see #129).

As a result, it makes more sense to brand this SDK as the "Watson Developer Cloud Swift SDK" instead of the "Watson Developer Cloud iOS SDK".

**Comment by schen22** [comment]
By adding basic support for Linux platform in this upcoming milestone, we're planning to rename ios-sdk to swift-sdk.

**Comment by schen22** [comment]
Due to changing the repo name, warnings will now show up when current users who have already cloned the repo: 
```bash
remote: This repository moved. Please use the new location:
remote:   git@github.com:watson-developer-cloud/swift-sdk.git
To git@github.com:watson-developer-cloud/ios-sdk.git
   44a0f0f..09573dd  your_branch_name -> your_branch_name
```

When publishing the release, remember to inform users something along the lines of the following - 

In order to dismiss and remove the warning git returns following any git changes pushed/pulled to the repo, run the following command within the repo's directory to update the remote's name:
- By SSH: `git remote set-url origin git@github.com:watson-developer-cloud/swift-sdk.git`.
- By HTTPS: `git remote set-url origin https://github.com/watson-developer-cloud/swift-sdk.git`.

 At the same time, if you're okay with receiving the warning, continue to push/pull as before. Taken from git documentation: "all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL."

**Comment by germanattanasio** [comment]
@SirSpidey should we update the sdk list in the wdc website?

**Comment by germanattanasio** [comment]
@schen22 you should also work with @mbouldin so that we can write a blog post for this here: https://developer.ibm.com/watson/blog/

**Comment by rfdickerson** [comment]
Oh wow! Didn't know the rename happened. This is great, I'll communicate this with the rest of the Swift@IBM team.

**Comment by schen22** [comment]
Just happened last night :) 

I'm planning to publish the release today, so I'll let you know when that happens for Linux users to start developing with the SDK.
