### ISSUE TITLE
Add streaming support

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/swift-sdk#221]
One of the good things about using opus is that we can stream results from the service to the speaker without having to use the memory.

Think about the scenario when you are writing an app that reads a book using TTS. You want to send the text and stream the synthesized audio back

**Comment by glennrfisher** [comment]
I figure we can continue the conversation about Text to Speech formats and streaming response data here.

Here are my thoughts:

- Before the Xcode 7.3 debacle, the Text to Speech implementation used Opus-encoded audio but did not stream the results to the consumer. Instead, the entire Opus file was downloaded and then converted to WAV since `AVFoundation` does not support Opus. So regardless of the format of the audio, the Text to Speech implementation did and still lacks support for streaming.

- I personally don't think the Text to Speech service should _ever_ return data with a corrupt header. Instead of advertising support for WAV, the Text to Speech service should instead support PCM (like Speech to Text). Text to Speech could then stream the data samples without have to add a corrupt WAV header. Consumers who wish to turn the data into a WAV file after all data has been downloaded would then be responsible for adding the header (just as they are responsible for fixing the header now).

- The Text to Speech service should add support for formats that are natively-supported on various platforms. Let's increase the adoption of Watson services by making them as easy as possible to consume.

- Consumers should be responsible for choosing the format they want to use. They receive data, so how they choose to process and play that data is at their discretion. Really, there's nothing we need to do to support Opus with Text to Speech other than to expose a format parameter.

**Comment by glennrfisher** [comment]
I've noticed that one of the biggest challenges with the iOS SDK is making things play nicely with Apple's libraries (along with their use of delegate functions, which we have been instructed to avoid).

For example, Alamofire [supports streaming](https://github.com/Alamofire/Alamofire/blob/master/Source/Request.swift#L135) but it isn't obvious how to return partial data to `AVFoundation` in a way that it can be easily consumed with the built-in audio player.

In contast, the Java SDK supports a very clean stream API that I assume is supported by various audio players natively.

**Comment by repjarms** [comment]
Closing as this is going to get packaged into an issue for the next major release.
