### ISSUE TITLE
Create sample application for Visual Recognition

### ISSUE THREAD

**Issue by glennrfisher** [watson-developer-cloud/swift-sdk#474]
Visual Recognition is a great service to demonstrate with iOS. We should create a sample application to perform object classification with images from an iPhone camera or photo roll.

It would be great if we could also upload pictures to create a training set, and put bounding boxes around recognized objects/faces.

Once the sample application is written, we should create a gif/video to include in its readme.

**Comment by bourdakos1** [comment]
I know this issue is pretty old, but I have a few sample apps showcasing visual recognition.

This project is what we have people build during our workshops and uses Watson trained Core ML models:
https://github.com/bourdakos1/visual-recognition-with-coreml/blob/master/README.md

I also have an older project (that doesn’t use the SDK, so would need updating) that lets you take photos for any of the cloud models and shows bounding boxes for the face model. It also allows you to create custom models directly from your phone, which you can immediately use in the classify UI.

**Comment by bourdakos1** [comment]
Here’s some photos of the other app if you’re interested:

![](https://i.imgur.com/2u4bJZh.jpg)

**Comment by repjarms** [comment]
@bourdakos1 this is very cool! I'm going to close this for now, but I'll connect with you soon about an upcoming update to our sample apps.
