### ISSUE TITLE
Mis matching audio listening most of times in iOS app

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [watson-developer-cloud/swift-sdk#636]
Its always mis matching the audio with text, suppose If I speak "Hello One Two Three" and its converting text from audio "Hello on duty", not only this, its like most of times showing mis word matching from audio, can you please suggest me how to fix this.

Platform : iOS with Objective-C.

**Comment by sccheng** [comment]
Hi, @AnilkumarRabhasa!

Thanks for opening this issue. I'm sorry to hear that you're having problems with the SpeechToText service!

Could you go ahead and try out this [demo](https://speech-to-text-demo.mybluemix.net/)? Let me know what the results are - if you receive the same errors from the online demo, it's possible that this is an issue with the service. If you don't see this issue, then we can try to figure out what other things might be causing the problem. Perhaps your microphone is covered, or the audio isn't recording clearly...

Regardless, please try out the demo and let me know what you see! Then, using your results, we can move forward from there.

**Comment by glennrfisher** [comment]
It's possible that your audio is being compressed, @AnilkumarRabhasa. You could try sending uncompressed audio (see the [Microphone Audio and Compression][1] section of the readme). The higher resolution of the audio may lead to better accuracy.

However, I suspect that your concerns are with the service's transcription accuracy rather than the SDK itself. If you'd like to leave a question or feedback for the service team, you can do so at one of the links provided in the [service documentation][2].

[1]: https://github.com/watson-developer-cloud/swift-sdk#microphone-audio-and-compression
[2]: https://www.ibm.com/watson/developercloud/doc/speech-to-text/index.html#feedback
