### ISSUE TITLE
[speech-to-text] Add support for mp3/mpeg contentTypes (and more)

### ISSUE THREAD

**Issue by cerupcat** [watson-developer-cloud/swift-sdk#649]
The online documentation (https://www.ibm.com/watson/developercloud/doc/speech-to-text/input.html) says there's support for contentTypes that are not available in the current SDK.

This seems to include: audio/mp3, audio/mpeg, audio/webm.

It would be nice to also support more native file types like m4a, caf, etc. Having to convert to a format that isn't common adds a lot of conversion code.

**Comment by glennrfisher** [comment]
Thanks for letting us know, @cerupcat!

This [commit][1] updates the SDK to support all of the formats listed in the Speech to Text documentation. Our team will review it then include it in the next published release.

At some point in the future, I think we will change the `AudioFormat` type to a `String` instead. This situation is a good argument _against_ enumerations, since changes are required to support new enum cases. Sorry for the inconvenience!

As for additional formats like m4a and caf, I don't think we will add them to the SDK. We added Opus to support a convenient and efficient way to stream microphone audio. But we generally want to keep the SDK lightweight. I think m4a and caf compression would best be handled by a different library.

[1]: https://github.com/watson-developer-cloud/swift-sdk/pull/654/commits/77c56f6a607fef48a9527c28a129c0b297e312ea
