### ISSUE TITLE
[speech to text] Timeout recognizing large files (>80MB)

### ISSUE THREAD

**Issue by sunil28011** [watson-developer-cloud/swift-sdk#693]
I am using this codes which always returns a TIMEOUT error for large files.

        var arr: NSMutableArray = NSMutableArray()
        var settings = RecognitionSettings(contentType:.mp3)        
        //  settings.continuous = true
        //  var mod = Model(json: RestKit.JSON)       
        //  settings.toJSON() = mod
        settings.inactivityTimeout = -1
        settings.interimResults = true
        settings.timestamps = true
        
        // settings.keywordsThreshold = 0.5
        settings.smartFormatting = true;
        
        // settings.wordAlternativesThreshold = 1
        let failure = {
            (error: Error) in print("error.localizedDescription= %@ and error = %@",error.localizedDescription,error) 
            let alert = UIAlertController(title: "Alert", message: error.localizedDescription, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
        }
        
        //        NSString * path = [urlStr path];
        //        NSString *theFileName = [[[path lastPathComponent] stringByDeletingPathExtension] stringByReplacingOccurrencesOfString:@"%20" withString:@""];
        //        theFileName = [NSString stringWithFormat:@"%@%@",@"sunil",theFileName];
        
        let strPath = self.speechSample .path as NSString
        
        var fileName : NSString = strPath.lastPathComponent as NSString
        fileName = fileName.deletingPathExtension as NSString
        
       //  fileName = self.language.appending(fileName as String) as NSString
       if self.language .isEqual(to: "English"){
         self.speechToText.recognize(audio: self.speechSample, settings: settings,failure: failure)
            {           
                results in
                self.textView.text = results.bestTranscript
                print("*** best: " + results.bestTranscript)
                print("*** results: " + results.results.description)
            }

**Comment by sunil28011** [comment]
I ma using this codes always get TIME OUT FOR large files.

        var arr: NSMutableArray = NSMutableArray()
        
        
        
        
        var settings = RecognitionSettings(contentType:.mp3)
        
        //      settings.continuous = true
        
     //   var mod = Model(json: RestKit.JSON)
        
        
      //  settings.toJSON() = mod
        settings.inactivityTimeout = -1
        settings.interimResults = true
        settings.timestamps = true
        
        //settings.keywordsThreshold = 0.5
        settings.smartFormatting = true;
        
        // settings.wordAlternativesThreshold = 1
        let failure = {
            (error: Error) in print("error.localizedDescription= %@ and error = %@",error.localizedDescription,error)
            
            
            let alert = UIAlertController(title: "Alert", message: error.localizedDescription, preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            
            
        }
        
        //        NSString * path = [urlStr path];
        //
        //        NSString *theFileName = [[[path lastPathComponent] stringByDeletingPathExtension] stringByReplacingOccurrencesOfString:@"%20" withString:@""];
        //        theFileName = [NSString stringWithFormat:@"%@%@",@"sunil",theFileName];
        
        let strPath = self.speechSample .path as NSString
        
        var fileName : NSString = strPath.lastPathComponent as NSString
        fileName = fileName.deletingPathExtension as NSString
        
       //  fileName = self.language.appending(fileName as String) as NSString
        
        
       
        
        if self.language .isEqual(to: "English"){
            
            
            self.speechToText.recognize(audio: self.speechSample, settings: settings,failure: failure)
            {
                
                results in
                self.textView.text = results.bestTranscript
                print("*** best: " + results.bestTranscript)
                print("*** results: " + results.results.description)
}

**Comment by glennrfisher** [comment]
Hi @sunil28011. I've been trying to replicate this issue for the last few days and haven't been able to do so. I tried a few large audio files, but was able to transcribe them completely.

Would you be willing to share the audio file you are trying to transcribe? That may be helpful for me to see if I can replicate the problem. Thanks!

P.S. The closest I could come to the problem was using `SpeechToTextSession`. I created a session, sent some audio, then stopped the microphone but did not stop the session. With the `inactivityTimeout` set to `-1`, the session timed out because no data was being sent through the socket. But it looks like you are using `SpeechToText` not `SpeechToTextSession`, so I don't think this applies to you.

**Comment by germanattanasio** [comment]
@sunil28011 what version of the sdk are you using?

**Comment by sunil28011** [comment]
@germanattanasio i using the latest one with xcode 9.1

**Comment by sunil28011** [comment]
@glennrfisher  i am currently  using this audio to convert speech to text [https://drive.google.com/file/d/1-YlQgzGMEX9i7lNn2uZNfZwj5xe5pfXo/view?usp=sharing](url). I always got the same issue of timeout after a few lines of transcription .

**Comment by germanattanasio** [comment]
is there a long silence in the audio?

**Comment by sunil28011** [comment]
@germanattanasio this problems happens for all the audio file which is grater than 50mb for me. Have you tried this sdk for large files like grater than 50 mb.

**Comment by glennrfisher** [comment]
Hi Sunil. I wrote a quick app to test your audio file and it worked alright
for me. I’m visiting with my family for the holidays, but will send more
information and upload the app for you to try in a few days. -Glenn

**Comment by sunil28011** [comment]
Hello glennrfisher. kindly upload that test app ASAP because of i am still struggling with this problem and  i m stuck with this since 1 month. THanks in advance

**Comment by glennrfisher** [comment]
Hi @sunil28011. Here's the [sample app][1] that you can try.

I scoured the underlying WebSockets library and found a way to change the internal socket timeout. Since the Speech to Text service has a [session timeout][2] of 30 seconds, I decided to enforce the same timeout with our underlying WebSockets library.

That change is in a pull request and should be released shortly. For the time being, I updated the sample app's `Cartfile` to specify the `timeout` branch and test the behavior of the longer timeout.

Even before modifying the timeout, I had no problem running the sample app in the simulator and on a test device. However, I did start to see socket write errors when enabling the network link conditioner and simulating a poor network connection. The longer timeout has seemed to improve performance on poor networks.

Unfortunately, the nature of speech transcription is such that it requires a healthy connection and strong bandwidth.

[1]: https://ibm.box.com/s/v53ba4wbho4e3t8f9aarhdslwryprhol
[2]: https://console.bluemix.net/docs/services/speech-to-text/websockets.html#WSkeep

**Comment by sunil28011** [comment]
i am getting the same issues with this build like previously. AudioTimeout[1403:31977] SocketStream write error [0x600000178180]: 1 60
The operation couldn’t be completed. Operation timed out. Don't know what's the reason for it. Overall thanks for your response and work.

**Comment by glennrfisher** [comment]
Sorry we couldn't find a better answer for you, @sunil28011. :(

**Comment by glennrfisher** [comment]
Hi @sunil28011. It turns out that Starscream—the library we use for the WebSocket session with Speech to Text—just released a new version 6 days ago. Among the changes is a "timeout fix." I wonder if this may help resolve the issue you encountered?

We're working to integrate the new version of Starscream into the Swift SDK and will leave another comment here once it's ready.

**Comment by sunil28011** [comment]
@glennrfisher  thanks for help
