### ISSUE TITLE
Is Watson Visual API support multiple classification other than the current positive and negative?

### ISSUE THREAD

**Issue by steve21124** [watson-developer-cloud/swift-sdk#770]
From below sdk. the test only positive and negative. Is the API support classification more than 1 category? like 10 categories with its own images
https://github.com/watson-developer-cloud/swift-sdk/blob/030568875a2520efaea8067052e49d794be9695a/Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift#L156

**Comment by glennrfisher** [comment]
Yup! Here's a [test][1] where we create a classifier with three classes: baseball, cars, trucks.

Although you may find it easier to create a custom classifier using the online tooling rather than the SDK. You can access the tool from the **Manage** page of your Visual Recognition instance.

![image](https://user-images.githubusercontent.com/1957636/37733572-7a4853b2-2d16-11e8-9245-277f750905ae.png)


The classes that are identified is within a lot of nested models when you run `classify`. You can simplify this if you know exactly what you're looking for, but here's a general example that prints the class and score for each image sent to Visual Recognition.

```swift
let failure = { (error: Error) in print(error) }
visualRecognition.classify(imagesFile: car, classifierIDs: [classifierID!], failure: failWithError) {
    classifiedImages in
    for image in classifiedImages.images {
        for classifier in image.classifiers {
            for cls in classifier.classes {
                let className = cls.className
                if let score = cls.score {
                    print("\(className): \(score)")
                }
            }
        }
    }
}
```

[1]: https://github.com/watson-developer-cloud/swift-sdk/blob/030568875a2520efaea8067052e49d794be9695a/Tests/VisualRecognitionV3Tests/VisualRecognitionTests.swift#L234
