### ISSUE TITLE
carthage update error

### ISSUE THREAD

**Issue by yuandonghua** [watson-developer-cloud/swift-sdk#780]
*** Downloading swift-sdk.framework binary at "v0.23.2"
*** Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.1 (swiftlang-902.0.48 clang-902.0.37.1)."

**Comment by glennrfisher** [comment]
Hi @yuandonghua. It looks like you've updated to Swift 4.1 / Xcode 9.3, which is why our Swift 4.0.3 binaries aren't compatible and need to be rebuilt on your machine.

We have a pull request (#778) which will update the project for Swift 4.1 / Xcode 9.3. We'll be publishing a release soon with binaries for Swift 4.1.

The build should succeed on your machine (unless you have SwiftLift, which introduced some new build errors with Xcode 9.3). If so, then it takes longer to get started with the Swift SDK, but it should work just as well.

**Comment by glennrfisher** [comment]
These warnings should be resolved now with [v0.23.3][1].

[1]: https://github.com/watson-developer-cloud/swift-sdk/releases/tag/v0.23.3
