### ISSUE TITLE
carthage build failed 

### ISSUE THREAD

**Issue by sanjeevghimire** [watson-developer-cloud/swift-sdk#791]
```
$ carthage bootstrap --platform iOS
Please update to the latest Carthage version: 0.29.0. You currently are on 0.23.0
*** No Cartfile.resolved found, updating dependencies
*** Fetching swift-sdk
*** Downloading swift-sdk.framework binary at "v0.23.3"
*** Checking out Starscream at "31f522155a4d6323cd1aaefb8dbc140ced7be1ca"
*** Skipped installing swift-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1 and the local version is 4.0.3."
*** Checking out swift-sdk at "v0.23.3"
*** xcodebuild output can be found in /var/folders/_h/4trwzcd908g703_vdw2q1yn00000gn/T/carthage-xcodebuild.AU1sFr.log
*** Building scheme "Starscream" in Starscream.xcodeproj
*** Building scheme "AssistantV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sanjeevghimire/Documents/projects/ResumeARIBM/ARBasedResumeWithFaceRecognition/Carthage/Checkouts/swift-sdk/WatsonDeveloperCloud.xcodeproj -scheme AssistantV1 -configuration Release -derivedDataPath /Users/sanjeevghimire/Library/Caches/org.carthage.CarthageKit/DerivedData/swift-sdk/v0.23.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_h/4trwzcd908g703_vdw2q1yn00000gn/T/carthage-xcodebuild.AU1sFr.log
```

**Comment by glennrfisher** [comment]
Hi @sanjeevghimire.

It looks like you're building with Xcode 9.2. If you have SwiftLint installed, you need to update to Xcode 9.3 to fix the build. SwiftLint parses the code differently with Xcode 9.3, and unfortunately causes a build error now with Xcode 9.2.

Aside from that, the build works normally on my machine and others. So I suspect something is funky with your environment. Here are some things that come to mind, in order from most likely to least likely to cause a problem:

1. Upgrade to Xcode 9.3 and make sure that it's configured for command-line use (Xcode Preferences -> Locations Tab -> Command Line Tools Dropdown). Xcode 9.3 comes with Swift 4.1, which will resolve the "incompatible Swift version" warning message.

2. Delete the `Carthage` directory. Use Xcode to clean the project (Product -> Clean). Also use Xcode to clean the build folder (Hold Option Key -> Product -> Clean Build Folder).

3. Update Carthage to the latest `0.29.0` version instead of `0.23.0`.

Hope that helps!
